### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by renlinch** [cutelyst/Virtlyst#13]
We need a User management, minimum Admin / User and maybe a Viewer.

(Only opened for Tracking)

**Comment by doanerock** [comment]
just use PAM and local accounts.  That should keep it simple.

**Comment by dantti** [comment]
I'd need to create a PAM plugin for the authentication module of Cutelyst, still this won't help with being able to create users that can't create machine and more fine grained roles

**Comment by victor-zorro** [comment]
I installed virtlyst in Arch linux. 
It works well (after some fiddling with settings) I had to delete the sql to start the initial setup again and grab the password. It works neat after that. Also to start I had to remove the two lines in the ini / socket file (a fastcgi at /run/virtlyst.sock (fastcgi better supports redirects)
and http for websockets at /run/virtlyst-ws.sock (since ws don't work with fastcgi)
 
I would also apply for user management, in a sort of way. But for now I wonder, is it possible to change the initial password or create one myself?

Keep up the good work, thanks.

**Comment by dantti** [comment]
To create PKDF password there is:
https://api.cutelyst.org/classCutelyst_1_1CredentialPassword.html#a2fd006ff22f6925762129b8aee1f1140

**Comment by dantti** [comment]
oh and be advised that UNIX sockets in Qt doesn't support threading or forking, it's an easy fix and it was reported to Qt, but nobody acted upon, also TCP sockets have SO_REUSEPORT which make them a much nicer alternative to UNIX sockets

**Comment by candlerb** [comment]
At worst you can manipulate the `users` table directly, but you still need a command line wrapper for `createPassword` - or a documented way to generate a compatible password hash using standard CLI tools.

(In which case it would also be helpful if the sqlite3 binary were included in the docker container)

**Comment by dantti** [comment]
User Management feature has been added to Virtlyst v2
