### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by millerjs2** [cutelyst/Virtlyst#21]
I'm interested in this, but there seems to be zero documentation regarding an actual implementation. Can you provide example documentation for how to actually get this running?

**Comment by dantti** [comment]
Well the example is on the README.md file, once it's compiled you just run it

**Comment by schnuffle** [comment]
I added some docs to the wiki, though it's still not easy to setup because of the dependencies to cutelyst, which itself has quite a lot of dependencies.
For that reason I proposed to build/run it in a Docker image.

I think the best would be to create distribution packages for the major distributions, that only need the runtime deps and not the build deps.
Maybe with some effort and help from all of us, we'll bring the docs and install process to a point where it's easy to use.

Regards

Schnuffle

**Comment by dantti** [comment]
For this project you only need Cutelyst built with Qt Core, Sql and Network modules, and with Grantlee plugin support. And libvirt which is required by Virtlyst.
There is also an OBS https://software.opensuse.org/package/cutelyst-devel and some distros already package it.
